package com.arpit.model;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Bank Value Object.
  * This class is value object representing database table bank
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Bank implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String account_number;
    private String name;
    private String branch;
    private String balance;
    private int employee_id;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Bank () {

    }

    public Bank (String account_numberIn) {

          this.account_number = account_numberIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getAccount_number() {
          return this.account_number;
    }
    public void setAccount_number(String account_numberIn) {
          this.account_number = account_numberIn;
    }

    public String getName() {
          return this.name;
    }
    public void setName(String nameIn) {
          this.name = nameIn;
    }

    public String getBranch() {
          return this.branch;
    }
    public void setBranch(String branchIn) {
          this.branch = branchIn;
    }

    public String getBalance() {
          return this.balance;
    }
    public void setBalance(String balanceIn) {
          this.balance = balanceIn;
    }

    public int getEmployee_id() {
          return this.employee_id;
    }
    public void setEmployee_id(int employee_idIn) {
          this.employee_id = employee_idIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String account_numberIn,
          String nameIn,
          String branchIn,
          String balanceIn,
          int employee_idIn) {
          this.account_number = account_numberIn;
          this.name = nameIn;
          this.branch = branchIn;
          this.balance = balanceIn;
          this.employee_id = employee_idIn;
    }


    /** 
     * hasEqualMapping-method will compare two Bank instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Bank valueObject) {

          if (this.account_number == null) {
                    if (valueObject.getAccount_number() != null)
                           return(false);
          } else if (!this.account_number.equals(valueObject.getAccount_number())) {
                    return(false);
          }
          if (this.name == null) {
                    if (valueObject.getName() != null)
                           return(false);
          } else if (!this.name.equals(valueObject.getName())) {
                    return(false);
          }
          if (this.branch == null) {
                    if (valueObject.getBranch() != null)
                           return(false);
          } else if (!this.branch.equals(valueObject.getBranch())) {
                    return(false);
          }
          if (this.balance == null) {
                    if (valueObject.getBalance() != null)
                           return(false);
          } else if (!this.balance.equals(valueObject.getBalance())) {
                    return(false);
          }
          if (valueObject.getEmployee_id() != this.employee_id) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Bank, mapping to table bank\n");
        out.append("Persistent attributes: \n"); 
        out.append("account_number = " + this.account_number + "\n"); 
        out.append("name = " + this.name + "\n"); 
        out.append("branch = " + this.branch + "\n"); 
        out.append("balance = " + this.balance + "\n"); 
        out.append("employee_id = " + this.employee_id + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Bank cloned = new Bank();

        if (this.account_number != null)
             cloned.setAccount_number(new String(this.account_number)); 
        if (this.name != null)
             cloned.setName(new String(this.name)); 
        if (this.branch != null)
             cloned.setBranch(new String(this.branch)); 
        if (this.balance != null)
             cloned.setBalance(new String(this.balance)); 
        cloned.setEmployee_id(this.employee_id); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
