package com.arpit.model;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Drivers Value Object.
  * This class is value object representing database table drivers
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Drivers implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int driver_id;
    private String license_number;
    private String expertise;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Drivers () {

    }

    public Drivers (int driver_idIn) {

          this.driver_id = driver_idIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getDriver_id() {
          return this.driver_id;
    }
    public void setDriver_id(int driver_idIn) {
          this.driver_id = driver_idIn;
    }

    public String getLicense_number() {
          return this.license_number;
    }
    public void setLicense_number(String license_numberIn) {
          this.license_number = license_numberIn;
    }

    public String getExpertise() {
          return this.expertise;
    }
    public void setExpertise(String expertiseIn) {
          this.expertise = expertiseIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int driver_idIn,
          String license_numberIn,
          String expertiseIn) {
          this.driver_id = driver_idIn;
          this.license_number = license_numberIn;
          this.expertise = expertiseIn;
    }


    /** 
     * hasEqualMapping-method will compare two Drivers instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Drivers valueObject) {

          if (valueObject.getDriver_id() != this.driver_id) {
                    return(false);
          }
          if (this.license_number == null) {
                    if (valueObject.getLicense_number() != null)
                           return(false);
          } else if (!this.license_number.equals(valueObject.getLicense_number())) {
                    return(false);
          }
          if (this.expertise == null) {
                    if (valueObject.getExpertise() != null)
                           return(false);
          } else if (!this.expertise.equals(valueObject.getExpertise())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Drivers, mapping to table drivers\n");
        out.append("Persistent attributes: \n"); 
        out.append("driver_id = " + this.driver_id + "\n"); 
        out.append("license_number = " + this.license_number + "\n"); 
        out.append("expertise = " + this.expertise + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Drivers cloned = new Drivers();

        cloned.setDriver_id(this.driver_id); 
        if (this.license_number != null)
             cloned.setLicense_number(new String(this.license_number)); 
        if (this.expertise != null)
             cloned.setExpertise(new String(this.expertise)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
