package com.arpit.model;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Loan Value Object.
  * This class is value object representing database table loan
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Loan implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int loan_id;
    private int source_id;
    private String amount;
    private java.sql.Date given_date;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Loan () {

    }

    public Loan (int loan_idIn) {

          this.loan_id = loan_idIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getLoan_id() {
          return this.loan_id;
    }
    public void setLoan_id(int loan_idIn) {
          this.loan_id = loan_idIn;
    }

    public int getSource_id() {
          return this.source_id;
    }
    public void setSource_id(int source_idIn) {
          this.source_id = source_idIn;
    }

    public String getAmount() {
          return this.amount;
    }
    public void setAmount(String amountIn) {
          this.amount = amountIn;
    }

    public java.sql.Date getGiven_date() {
          return this.given_date;
    }
    public void setGiven_date(java.sql.Date given_dateIn) {
          this.given_date = given_dateIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int loan_idIn,
          int source_idIn,
          String amountIn,
          java.sql.Date given_dateIn) {
          this.loan_id = loan_idIn;
          this.source_id = source_idIn;
          this.amount = amountIn;
          this.given_date = given_dateIn;
    }


    /** 
     * hasEqualMapping-method will compare two Loan instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Loan valueObject) {

          if (valueObject.getLoan_id() != this.loan_id) {
                    return(false);
          }
          if (valueObject.getSource_id() != this.source_id) {
                    return(false);
          }
          if (this.amount == null) {
                    if (valueObject.getAmount() != null)
                           return(false);
          } else if (!this.amount.equals(valueObject.getAmount())) {
                    return(false);
          }
          if (this.given_date == null) {
                    if (valueObject.getGiven_date() != null)
                           return(false);
          } else if (!this.given_date.equals(valueObject.getGiven_date())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Loan, mapping to table loan\n");
        out.append("Persistent attributes: \n"); 
        out.append("loan_id = " + this.loan_id + "\n"); 
        out.append("source_id = " + this.source_id + "\n"); 
        out.append("amount = " + this.amount + "\n"); 
        out.append("given_date = " + this.given_date + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Loan cloned = new Loan();

        cloned.setLoan_id(this.loan_id); 
        cloned.setSource_id(this.source_id); 
        if (this.amount != null)
             cloned.setAmount(new String(this.amount)); 
        if (this.given_date != null)
             cloned.setGiven_date((java.sql.Date)this.given_date.clone()); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}


